#!/usr/bin/env bash

CONTAINER_TAG=dagger-tests

set -e
echo "Building dagger testing container..."
docker build --quiet -t ${CONTAINER_TAG} --file tests/_inf/Dockerfile .
docker run -it --rm -v ${PWD}:/home/dagger/dagger ${CONTAINER_TAG} $@
